#!/bin/bash

make && \
qemu-system-x86_64 \ 
	-nographic -smp 1 \ 
	-d int,cpu_reset -D build/qemu.log \
	-accel tcg,thread=multi \ 
	-serial mon:stdio \
	-drive format=raw,file=build/kernel-x86_64-qemu

