#!/bin/bash

qemu-system-x86_64 -s -S -nographic -serial none -machine accel=tcg -smp 1 -drive format=raw,file=build/thread-os-x86_64-qemu &
pid=$!
gdb \
  -ex "target remote localhost:1234" \
  -ex "set confirm off" \
	-ex "file build/thread-os-x86_64-qemu.o"

kill -9 $!
